#! /bin/sh

pkill sxhkd
sxhkd &

setxkbmap latam
xrandr -s 1366x768  -r 60.00

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

nitrogen --restore &
picom -f &

bspc rule -a Zathura state=tiled

bspc monitor -d I II III IV V IV 

bspc config border_width               1
bspc config window_gap                 12
bspc config focused_border_color      '#61ffaf'
bspc config normal_border_color       '#000000'
bspc config active_border_color       '#ffffff'
bspc config presel_feedback_color     "#373737"

bspc config top_padding     1 
bspc config bottom_padding  1 
bspc config left_padding    1 
bspc config right_padding   1

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config click_to_focus            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true


bspc rule -a Gimp desktop='V' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
